import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  name: "viewport",
  content: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-montserrat overflow-x-hidden">
        <div className="lg:bg-[url('/assets/bg.jpg')] lg:bg-cover">
          <div className="bg-white z-50">
            <Navbar></Navbar>
            {children}
          </div>
        </div>

        <div className="bg-[#251c5d]">
          <div className="">
            <Footer></Footer>
          </div>
        </div>
      </body>
    </html>
  );
}
